### PR TITLE
[fix]:  -[NSNull mj_keyValues] will crash running on iOS 13

### PR DESCRIPTION
**Pull request by Neil20170223**
-[NSNull mj_keyValues] will crash running on iOS 13 developer beta 1

### CODE REVIEW

**Comment by wolfcon** [comment]
not happen as I test

**Comment by chenshengzhi** [comment]
图片
暂时只能在公司项目里必现, 我晚上写个 demo 试试.

**Comment by wolfcon** [comment]
你这个咋感觉像是死循环了...

**Comment by Neil20170223** [comment]
是的. NSNull 类会

**Comment by chenshengzhi** [comment]
是的. 还是主线程.

**Comment by wolfcon** [comment]
discuss in #692

**Pull request closed without merging**
